export interface GoldenQuery {
  q: string;
  expect: string[];
}

export const GOLDEN: GoldenQuery[] = [
  { q: "vakum na mizi ne drži", expect: ["kb_005", "kb_t003", "kb_t052"] },
  { q: "tiskalan glava zamasena", expect: ["kb_001", "kb_t065", "kb_t005"] },
  { q: "E-042", expect: ["kb_003", "kb_t001"] },
  { q: "e042 crpalka", expect: ["kb_003", "kb_t001"] },
  { q: "proge na sijajnem materialu", expect: ["kb_002", "kb_t011"] },
  { q: "nož reže razcefran rob", expect: ["kb_012", "kb_t014", "kb_t009"] },
  { q: "vreteno se pregreva", expect: ["kb_t038", "kb_008"] },
  { q: "mehurčki v laku", expect: ["kb_009", "kb_t017"] },
  { q: "mehurcki na laminatu", expect: ["kb_t007"] },
  { q: "kompresor pada tlak", expect: ["kb_016", "kb_t075"] },
  { q: "omrezje v pakirnici pada", expect: ["kb_t046"] },
  { q: "licenca caldera potekla", expect: ["kb_t026"] },
  { q: "RIP se zatakne vrsta", expect: ["kb_017"] },
  { q: "disk poln na postaji", expect: ["kb_t020"] },
  { q: "var ne drzi na debelem pvc", expect: ["kb_t033", "kb_010"] },
  { q: "trak se zatika v stroju za povezovanje", expect: ["kb_013", "kb_t056"] },
  { q: "spoj ne drzi povezovalnik", expect: ["kb_014", "kb_t060"] },
  { q: "klima ne hladi v hali", expect: ["kb_t050"] },
  { q: "alarm filtra prezracevanje", expect: ["kb_015", "kb_t086"] },
  { q: "streha pusca voda kaplja na mize", expect: ["kb_t022"] },
  { q: "barva se spreminja pri dolgi nakladi", expect: ["kb_t025"] },
  { q: "razlika v barvah med dvema strojema", expect: ["kb_t023", "kb_019"] },
  { q: "tangencialni noz preskakuje v krivinah", expect: ["kb_007", "kb_t029"] },
  { q: "stroj ne prepozna orodja", expect: ["kb_t021"] },
  { q: "madezi na hrbtni strani plosc", expect: ["kb_t085"] },
  { q: "bela je motna", expect: ["kb_t069"] },
  { q: "crnilo kaplja na material", expect: ["kb_t031"] },
  { q: "stroj se ustavi napaka krmilnika", expect: ["kb_t076"] },
  { q: "sušilnik se pregreje pri polni hitrosti", expect: ["kb_t084"] },
  { q: "toplotni tunel ne greje", expect: ["kb_t049"] },
  { q: "kontura se ne ujema z odtisom", expect: ["kb_t062"] },
  { q: "zunanji disk se odklopi", expect: ["kb_t066"] },
  { q: "NAS disk opozorilo SMART", expect: ["kb_t078"] },
  { q: "varnostna kopija ni uspela", expect: ["kb_t036"] },
  { q: "štampač glava ne radi, dizne začepljene", expect: ["kb_001", "kb_t065", "kb_t005"] },
  { q: "vakuum ne drži materijal na stolu", expect: ["kb_005", "kb_t003", "kb_t052"] },
  {
    q: "Med rezanjem velike pole se material premika, na zadnjih conah mize manometer kaže nizek podtlak in se sliši sikanje",
    expect: ["kb_t003", "kb_005"],
  },
  { q: "oscilirno orodje se ustavlja v peni", expect: ["kb_t015"] },
  { q: "zasilna luc ne sveti", expect: ["kb_t006"] },
  { q: "ne morem se povezati na vpn", expect: ["kb_022"] },
  { q: "postaja se počasi zaganja", expect: ["kb_t053"] },
  { q: "podajanje role neenakomerno", expect: ["kb_t044"] },
  { q: "rola se zatika pri odvijanju", expect: ["kb_t072"] },
  { q: "lažni računi v e-pošti", expect: ["kb_t070"] },
  { q: "manjkajoče pisave v pdf", expect: ["kb_t034"] },
  { q: "nozno stikalo", expect: ["kb_011"] },
  { q: "senzor sirine medija", expect: ["kb_t019"] },
  { q: "glava zadela ob ploščo", expect: ["kb_t054", "kb_004"] },
  { q: "poševen rez na desni strani", expect: ["kb_t058"] },
  { q: "rezalna podloga", expect: ["kb_t045"] },
  { q: "Stroj javlja napako podtlaka in se ustavi pred tiskom", expect: ["kb_t001", "kb_003"] },
];
